source 'https://github.com/CocoaPods/Specs.git'

target 'iPerspective', :exclusive => true do
  pod "iPerspective", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "iPerspective", :path => "../"

  
end
